### ISSUE TITLE
在IE8下不可用，缺少依赖es5-shim

### ISSUE THREAD

**Issue by codering** [CFETeam/bee.js#7]
我用的build目录下的bee.js, IE8下无法运行，加上src下的es5-bee-shim.js就可以了。

**Comment by justan** [comment]
是这样的. es5-shim 需要自行添加

**Comment by codering** [comment]
@justan 你好。 我是在google IE8的自定义标签时看到beejs 的，不知现在可以用于生产环境吗?

**Comment by justan** [comment]
我们自己是有用的. 适不适合你们得你自己评估了..

**Comment by codering** [comment]
恩，谢谢
